# Generated by Django 5.0.3 on 2024-03-29 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_alter_bookmarks_user_alter_likes_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='grades',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='manga.manga'),
        ),
    ]
